### ISSUE TITLE
Header on small screens looks pretty lousy

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_GENFINPLAN#6]
![Screenshot 2016-12-20 12.50.45](http://static.gitscout.com/dae87e0c45c1dd86c4ec5f3bf64e86fdac3ee26c0fd61eae63329b1872c2c692.png)

I think we should do our best to make the phone numbers line up nicely. Or maybe make tapping the phone icon bring up both numbers so you can select which to call. That'd be sweet.

The Customer Login link also looks bad. It's supposed to be fixed in the upper right. I think it should either move into the main menu or just go in the upper right corner, fixed to the top.

**Comment by d4mation** [comment]
The two phone numbers are a single field in the Database that strips out any HTML, so using some CSS breakpoints I did my best to get them on two lines on different mobile sizes. Also, that Customer Login button is now fixed in the corner for each screen size.

Mobile:
![image](https://cloud.githubusercontent.com/assets/7770631/21550939/a316cb58-cdcb-11e6-81f8-6af7a4ba571e.png)

Desktop:
![image](https://cloud.githubusercontent.com/assets/7770631/21550949/af9d9578-cdcb-11e6-880d-9a9058b929fa.png)
