### ISSUE TITLE
Multiple locations on map on contact page

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_GENFINPLAN#8]
The contact page has a map but it only shows one location. We either need to add a second map or make the map have two markers on it.

**Comment by d4mation** [comment]
This has been implemented, but it isn't something easy to change. Google Maps requires you to either use their API or use a pre-generated Map via Map Maker to have multiple markers. I opted for using a pre-generated map since I don't think it will change too often (if at all) and writing something using their API would likely have been overkill. Also, I think two maps would have looked messy 🤐

**Comment by joelworsham** [comment]
I recall dealing with the maps API a while back for having multiple locations. http://www.vk1call.com/contact-us/

I don't remember exactly how I did it, but it wasn't too bad!

https://github.com/realbig/VanDamTheme/blob/master/templates/contact.php

**Comment by joelworsham** [comment]
VanDam example is cool because they could add the address via post meta on the template page, and that was dynamically added to the map as markers.

**Comment by joelworsham** [comment]
https://github.com/realbig/VanDamTheme/blob/master/assets/js/source/googlemaps.js
